### ISSUE TITLE
Some mails / folders are not correctly count: mailing-lists, X-bcc, Indetities management

### ISSUE THREAD

**Issue by Valeryan24** [devmount/third-stats#280] opened 2021-03-14 17:57 UTC
Hi, first thanks a lot for this great and complete addon, compatible with Thunderbird 78 !

**Describe the bug**
Third-Stats doesn't count emails (received or sent) in some cases or folders / identities.

**To Reproduce**
- Folders with only mails from mailing-list, where our address doesn't appear in "To" nor "Cc" field, but is in X-bcc : it tells me 0 mail (empty)
- Folders with emails not sent to us, but that we would like to be treated as received mails (added in Imap from another account via copy)
- Identities : how many max can we put in the account settings? Please make them not case-sensitive, to reduce the number to treat.
- Sometimes a folder is well counted, and on the next Thunderbird restart, without having modified it (no mail received / sent or moved) but just having changed settings (identities), no more mails or just a few part is seen, and stat changes.

I know my explanations are not very precise, but for some folders I don't understand why emails are not recognized or change (and I well entered all my identities). I have "Identity chooser" addon installed, too (https://addons.thunderbird.net/fr/thunderbird/addon/identity-chooser/), and I unthick some identities in its settings to avoid having a too long list proposed on a compose message window (but all are still on TB mail account settings),I didn't see that it was a conflict but in case of, I notice it.

**System (please complete the following information):**
- OS: Ubuntu 21.04
- Thunderbird Version 78.8.0 (64-Bit)]

**Additional context**
If possible it could be great to have some options:
- when a folder is selected, having a box to thick if we want only itself to be tested or all its subfolders - for example, in my "Sent" folder ("Envoyés" in French), I have many subfolders, like in my Inbox (for private mails, job, shopping…). ANd if I select "Sent", Third-STats only processes the main folder.
- add a tag to a folder : for example, all what is is "Sent" and subfolders are sent mails and all should be counted for the stats. All what is Inbox or subfolders are "received mails", or we could choose folder by folder. It would "force" Third-Stats to act like this, no matter how it attributes itself the mails.
- possibility to exclude some (sub)-folders from the analysis - for example if I want to compare stats with and without mailing-lists

It's more for the statistic purpose of time (day, hour) of mails received / sent which is very interesting but needs that all mails are treated.

Thanks again :+1:

**Comment by devmount** [comment] 2021-03-19 08:31
Hi Xavier,

thank you for this detailed report. Some more details are needed here to solve your problems.

> Folders with only mails from mailing-list, where our address doesn't appear in "To" nor "Cc" field, but is in X-bcc : it tells me 0 mail (empty)

The ThirdStats logic is: If the author of an email matches any configured identity (either in Thunderbird or for local accounts in the add-on options) it is recognized as "sent", otherwise as "received". If no email is recognized at all, there seems to be another issue, probably with the folder itself. Can you check if this maybe a cause of this issue:
https://github.com/devmount/third-stats/issues/239#issuecomment-773606896

> Folders with emails not sent to us, but that we would like to be treated as received mails (added in Imap from another account via copy)

You can achieve this by simply configuring the corresponding email addresses as identity (Thunderbird > right click on account > Settings > Manage Identities).

> Identities : how many max can we put in the account settings? Please make them not case-sensitive, to reduce the number to treat.

There is no limit and they are case-insensitive already. If you experience something else, please issue [a dedicated bug report](https://github.com/devmount/third-stats/issues/new?assignees=&labels=&template=bug_report.md).

> Sometimes a folder is well counted, and on the next Thunderbird restart, without having modified it (no mail received / sent or moved) but just having changed settings (identities), no more mails or just a few part is seen, and stat changes.

This needs a little more detailed descriptions. What do you do exactly where in which order? I can try to reproduce it on my end then.

> I have "Identity chooser" addon installed, too

I see, I don't know this add-on and what it does under the hood, but this may be a possible reason for your issues. If possible, you can try to disable it and see, if your ThirdStats issues still occur. Unfortunately I can't provide support integrating ThirdStats with other add-ons.

> when a folder is selected, having a box to thick if we want only itself to be tested or all its subfolders - for example, in my "Sent" folder ("Envoyés" in French), I have many subfolders, like in my Inbox (for private mails, job, shopping…). ANd if I select "Sent", Third-STats only processes the main folder.

Yes, this was a design decision to improve perfomance on filtering for single folders. But it's totally possible to implement an add-on option to activate recursive folder processing for the folder filter. Please issue [a dedicated feature request](https://github.com/devmount/third-stats/issues/new?assignees=&labels=&template=feature_request.md) for this.

> add a tag to a folder : for example, all what is is "Sent" and subfolders are sent mails and all should be counted for the stats. All what is Inbox or subfolders are "received mails", or we could choose folder by folder. It would "force" Third-Stats to act like this, no matter how it attributes itself the mails.

A configurable list of folders to recognize as sent, it's possible to implement this as additional add-on option. Please issue [a dedicated feature request](https://github.com/devmount/third-stats/issues/new?assignees=&labels=&template=feature_request.md) for this.

> possibility to exclude some (sub)-folders from the analysis - for example if I want to compare stats with and without mailing-lists

A configurable list of folders to exclude from analysis at all, it's possible to implement this as additional add-on option. Please issue [a dedicated feature request](https://github.com/devmount/third-stats/issues/new?assignees=&labels=&template=feature_request.md) for this.

Thank you, for your ideas and suggestions!

**Comment by devmount** [comment] 2021-04-25 18:29
@Valeryan24 Do you need anything more? Otherwise I'll close this.

**Comment by Valeryan24** [comment] 2021-04-26 06:06
Sorry, I didn't take time for the moment to make the feature requests. Thanks a lot for your answer - yes you can close this issue, and I will write the FR !

**Comment by devmount** [comment] 2021-04-26 06:07
Alright! Thanks again for your time and ideas 👏🏻

**Closed by devmount** 2021-04-26 06:07 UTC
Labels: question

**Comment by devmount** [comment] 2023-03-31 09:38
FYI: The recursive folder filter feature is now requested in #407
