### ISSUE TITLE
List of accounts not fully displayed

### ISSUE THREAD

**Issue by rfwolff** [devmount/third-stats#191] opened 2020-12-27 13:51 UTC
List of accounts not fully displayed when clicking the ThirdStats button.

To reproduce:
Click on ThirdStats button (Thunderbird main window / Mail toolbar). Eight accounts found but only 6.5 of these are displayed (list cut off), i.e. seven are clickable, local accounts is missing (out of view).

Expected behaviour:
Display all accounts, e.g. include scrollbar if not all accounts can be displayed.

System:
- Windows 10 Pro 1909
- Thunderbird 78.6.0
- ThirdStats 1.1.1

**Comment by devmount** [comment] 2020-12-28 12:24
Thank you for reporting this. It's caused by a max-height set by Thunderbird for popup menus. Will be fixed in the next release.

**Comment by rfwolff** [comment] 2020-12-28 14:33
Excellent, thank you. Looking forward to the new version.

**Comment by devmount** [comment] 2021-01-04 10:15
This got implemented with #198. Account tiles are now two column and overflow content can be reached via scrolling.

**Closed by devmount** 2021-01-04 10:15 UTC
Labels: bug, design, ux
