### ISSUE TITLE
Drop-down controls (week start, self messages) in Options do not expand

### ISSUE THREAD

**Issue by koobs** [devmount/third-stats#235] opened 2021-01-31 02:09 UTC
**Describe the bug**
--

Drop-down controls ```week start``` and ```self-messages``` in ThirdStats -> Options -> Charts & Data do not "expand" (drop down) when clicked

**To Reproduce**
--
1. Open ```ThirdStats -> Options -> Charts & Data```
2. Click drop-down controls for ```Start the week on``` and ```Self-Messages``` Options

**Expected behavior**
--

Drop-down control expands displaying mutually exclusive values (days of the week, etc)

**Current Behaviour**
--

Nothing happens

**Screenshots**
--

![106372510-4fb5df80-6368-11eb-9934-8180375e9fa4](https://user-images.githubusercontent.com/1011612/106411225-9ffe7180-643c-11eb-81df-c24777a42360.png)

**System (please complete the following information):**
--
- OS: Windows 10 Pro (20H2) Build 19042.746
- Thunderbird Version: Daily (87.0a1 (2021-01-30) (64-bit)

**Comment by devmount** [comment] 2021-01-31 06:49
Thank you for testing ThirdStats on TBs daily build 👏🏻 This is a great help! I can confirm this issue even for TB 86.0.

**Comment by koobs** [comment] 2021-02-01 03:22
@devmount ❤️

**Comment by devmount** [comment] 2021-02-03 05:12
I did some additional testing and it looks like a TB issue. I placed [a corresponding post add Thunderbirds topicbox](https://thunderbird.topicbox.com/groups/addons/T73f12f5aa7afb6eb/no-drop-down-content-of-form-input-elements-is-shown-in-tb-86), let's hope somebody else is experiencing this too and has a solution.

**Comment by devmount** [comment] 2021-02-03 12:25
It's confirmed that this is a TB issue and filed here: https://bugzilla.mozilla.org/show_bug.cgi?id=1690514

As a workaround, you can toggle the `browser.tabs.remote.autostart` preference and restart Thunderbird. Since this isn't ThirdStats related, I'll close this here.

**Closed by devmount** 2021-02-03 12:25 UTC
Labels: bug, thunderbird issue

**Comment by koobs** [comment] 2021-02-09 05:56
Confirmed working in latest Daily
