### ISSUE TITLE
Sent mail statistics are zero (0) in 90.0a1 (Windows 64-bit)

### ISSUE THREAD

**Issue by koobs** [devmount/third-stats#317] opened 2021-05-31 03:32 UTC
**Describe the bug**

Statistics for Sent mail are zero (0) for at least the past couple of weeks. I am not sure when the issue was first introduced.

**To Reproduce**
1. Go to ThirdStats Dashboard
2. Observe no stats for "Mails sent"
3. Try to rebuild cache
3. Observe no stats for "Mails sent" again

**Expected behavior**

Up-to-date and accurate statistics for Sent mail

**Screenshots**

![sshot-2021-05-31-13-31-20](https://user-images.githubusercontent.com/1011612/120135900-c224b800-c1c0-11eb-8c79-39c75ae07957.png)

**System (please complete the following information):**

- OS: Windows 10 Pro 20H2 x64 19042.1023
- Thunderbird Version: 90.0a1 (2021-05-30) (64-bit)

**Additional context**

 * Isolation tests: rebuild cache. enable service workers (warning in dev console)

Developer Console messages:

![sshot-2021-05-31-13-23-30](https://user-images.githubusercontent.com/1011612/120135780-825dd080-c1c0-11eb-9f8d-67ddd4568c14.png)

**Comment by devmount** [comment] 2021-05-31 04:23
Thank you for this report. I'm unable to reproduce this on Win10/TB90.0a1 so let's try to narrow it down:

1. Since it stopped working at some point I assume all your identities are correctly configured? Is this a local or an IMAP account?
2. Do you have "Messages to Self" enabled in the add-on options?
3. Do you only use Thunderbird Daily or do you also have a Thunderbird Beta / Stable on your machine to confirm, that this bug is related to the Daily version?

**Comment by koobs** [comment] 2021-06-03 01:41
1. Google IMAP Account
2. Test with `Reset Options` which disables Self messages. 
3. I only use Daily, but I tested back to 2021-04-03 (89.0). Unfortunately, there's the virtual folder bug before 2021-04-29. Build bisection:

```
2021-04-03 (89.0a1) - TS doesn't complete processing - Error: Folder not found: <virtualfoldername>
2021-04-17 (89.0a1) - TS doesn't complete processing - Error: Folder not found: <virtualfoldername>
2021-04-24 (90.0a1) - TS doesn't complete processing - Error: Folder not found: <virtualfoldername>
2021-04-28 (90.0a1) - TS doesn't complete processing - Error: Folder not found: <virtualfoldername>
2021-04-29 (90.0a1) - Not OK 
2021-04-30 (90.0a1) - Not OK 
2021-05-03 (90.0a1) - Not OK 
2021-06-02 (91.0a1 )- Not OK
```

4. I've also reset almost all custom preferences back to defaults.

**Comment by koobs** [comment] 2021-06-03 02:13
Inspecting extension data storage:

![sshot-2021-06-03-12-10-08](https://user-images.githubusercontent.com/1011612/120575730-1f16ad00-c411-11eb-88b7-b45bdf2c7c8e.png)
...snip...

![sshot-2021-06-03-12-10-24](https://user-images.githubusercontent.com/1011612/120575732-1faf4380-c411-11eb-9111-3dbb78a7582b.png)
...snip...

![sshot-2021-06-03-12-10-41](https://user-images.githubusercontent.com/1011612/120575735-2047da00-c411-11eb-8f49-5146eb0a51ca.png)
...snip...

![sshot-2021-06-03-12-11-08](https://user-images.githubusercontent.com/1011612/120575737-20e07080-c411-11eb-9731-6f8f04e463fe.png)

**Comment by devmount** [comment] 2021-06-03 04:23
I see, sorry to hear that you are affected by the virtual folder bug (I thought that was fixed long before TB 90 😮).

Since I haven't been able to find what's causing this issue on my end, I created a debug version of ThirdStats for you. Please install the following ThirdStats add-on (rename the file extension from .zip to .xpi first):
[third-stats_v1.8.0-alpha.sent-received-recognition.zip](https://github.com/devmount/third-stats/files/6588908/third-stats_v1.8.0-alpha.sent-received-recognition.zip)

Open the stats tab, open the console, clear it and process the affected account again. It will log all messages to the console showing you, if ThirdStats recognized them as sent or received like this:
![image](https://user-images.githubusercontent.com/5441654/108087768-09ef5b80-7078-11eb-9284-917e0fad33c1.png)

You now have the possibility to go through that list, analyze the message objects and hopefully see, why ThirdStats doesn't correctly recognized your sent mails. Note that this will produce one console entry per email, so be patient as it can take some time to process especially large accounts. Let me know, if you found anything of interest.

**Comment by koobs** [comment] 2021-06-03 04:47
@devmount Only saw virtual folder issue using older versions while bisecting :)

Thank you for the debug version. Will test and report back. 

Relatedly, I think it'd be worthwhile, if its possible, to add a 'Debug' option to ThirdStats to allow for quicker and simpler user debugging in the future for situations like these. Certainly save the time going back and forth :)

Do you want a new issue for that?

**Comment by devmount** [comment] 2021-06-03 12:22
> Only saw virtual folder issue using older versions while bisecting :)

Bisecting? Sorry if there was a joke, I didn't get it 🙈 

> Relatedly, I think it'd be worthwhile, if its possible, to add a 'Debug' option to ThirdStats to allow for quicker and simpler user debugging in the future for situations like these. Certainly save the time going back and forth :)

Great suggestion. As [I stated here](https://thunderbird.topicbox.com/groups/addons/T9721f6fb5b4fda2e/end-user-tests-bug-hunting-and-logging), the demand for such a feature is too small by now, but I totally see that this would be useful.

Would be awesome if you could create a new issue for that - as I really like reading issues from you anyway 😍

**Comment by koobs** [comment] 2021-06-04 03:59
Hey Andreas. Tried to let the debug/refresh run three times to completion but thunderbird crashes every time after consuming all memory (16gb)

Can we descope the debug to only include sent, or exclude received or something?

Also I think I found an unrelated bug ;)

**Comment by devmount** [comment] 2021-06-04 04:15
Whoa, I see - so logging 64k mail objects to the console wasn't the brightest idea here 🙈 I rebuild the debug version without logging the whole object, so this should fit now into your memory (at least I hope so):

[third-stats_v1.8.0-alpha.sent-received-recognition.2.zip](https://github.com/devmount/third-stats/files/6595727/third-stats_v1.8.0-alpha.sent-received-recognition.2.zip)

> Also I think I found an unrelated bug ;)

Looking forward to your bug report ;)

**Comment by koobs** [comment] 2021-06-07 06:49
Test results:

 * All log entries are prefixed [RECEIVED]. I see no other entries.
 * Only two errors observed, one which I've seen before, and don't know if its related to thirdstats or not, but im guessing not (The 5 minute activity manager thread possible?) (see screenshot). I see this error at intervals unrelated to thirdstats processing too. The other error is that which is included in the screenshot in the original report.
 * I mentioned "unrelated bug" in my last post. I mention here in case its relevent :)
   * Some entries contain `[RECEIVED] foo@barbsd.org not found in ["foo@BarBSD.org"]` (note: same email, case difference). My naive expectation would be that this would or should be a match, if the check was case-insensitive. Still, this is only for [RECEIVED] (I see no [SENT]). I can report this separately if its unrelated to this issue.
   * I also see entries like `[RECEIVED] foo@bar.tld some other text not found in ["foo@BarBSD.org"]`. The actual examples of 'some other text' are like firstname lastname, or (nickname something). My naive expectation would be whatever API is being used to extract email addresses, would *only* return email addresses, not email addresses plus additional text.

![sshot-2021-06-07-16-38-29](https://user-images.githubusercontent.com/1011612/120970688-48aa3e00-c75b-11eb-9008-bde6af39be7f.png)

**Comment by devmount** [comment] 2021-06-10 08:59
Thanks again for your detailed report.

Error 1: As you already guessed, this isn't related to ThirdStats.
Error 2: This is indeed a ThirdStats issue. Actually, everything should be normalized to lower case, but thanks to your report I found some places where this transformation was still missing. I also improved the email address recognition algorithm in strings. Here is a fixed version, can you test this again?

[third-stats_v1.8.0-alpha.sent-received-recognition.3.zip](https://github.com/devmount/third-stats/files/6629826/third-stats_v1.8.0-alpha.sent-received-recognition.3.zip)

**Comment by koobs** [comment] 2021-06-14 00:44
You win @devmount. Sent mail stats are back. So root causes was a case-insensitive match and I'm one of those annoying users who breaks thing? :)

**Comment by koobs** [comment] 2021-06-14 00:45
Have a couple more comments to add, but need some more time to flesh out

**Comment by devmount** [comment] 2021-06-14 03:11
Great! Thanks for confirming the fix, will be part of the next release.

> Have a couple more comments to add, but need some more time to flesh out

Take your time.

**Closed** 2021-07-05 18:56 UTC
Labels: bug
