### ISSUE TITLE
Ignore saved searches

### ISSUE THREAD

**Issue by orgoj** [devmount/third-stats#223] opened 2021-01-22 11:21 UTC
ThirdStats hang on updating stats on account if it contains save searched as folder.

In extension debug console is:
Uncaught (in promise) Error: Folder not found: /SAVED_SEARCH_FOLDER_NAME   undefined

**Comment by devmount** [comment] 2021-01-23 06:06
Hi Michael,

thank you for reporting this. How did you create that save search folder? Directly in Thunderbird (if so, which steps did you take?) or on your mail server before it got synced to Thunderbird?

**Comment by orgoj** [comment] 2021-01-23 08:13
Hi Andreas,

directly in Thunderbird. Right click any IMAP foleder, select Search Messages, fill some search criteria, click button Save as Search Folder (default is selected under originating IMAP folder).

**Comment by devmount** [comment] 2021-01-24 13:15
Ok, I've done exactly like you described - but I don't get any error messages and processing finishes as intended.

Can you please provide the full error stack and all information from the issue template for bug reports? Thanks.

**Comment by orgoj** [comment] 2021-01-24 14:49
OS: Ubuntu 20.04
Thunderbird: from ppa:mozillateam/ppa 78.6.1 (64-bit)
Thunderbird account is IMAPS with cca 30 folders (6 saved searches) 60000 mails

Console log of extension
<details>
<summary>Details</summary>

14:53:17.882 debuggee 'resource://devtools/shared/base-loader.js:289' would run builtin-modules.js:180:9
14:53:19.839
Unknown property ‘-moz-stack-sizing’.  Declaration dropped. chat.css:17:21
14:53:19.870
Error in parsing value for ‘box-sizing’.  Declaration dropped. start-style.css:96:15
14:53:19.870
Error in parsing value for ‘box-sizing’.  Declaration dropped. start-style.css:152:15
14:53:19.870
Error in parsing value for ‘box-sizing’.  Declaration dropped. start-style.css:212:15
14:53:19.878
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. fontawesome-all.css:10:27
14:55:45.797 Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”). panel.js:78:24
14:55:46.238 Webconsole context has changed
14:55:46.610 Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”). 2 panel.js:78:24
14:56:47.995
Error: CallResult for closed conduit thirdstats@devmount.de.82: ({childId:"thirdstats@devmount.de.82", callId:85, path:"tabs.create", result:{}}) ConduitsChild.jsm:179:13
    receiveMessage resource://gre/modules/ConduitsChild.jsm:179
14:56:49.454 Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”). panel.js:78:24
14:56:49.664
Uncaught (in promise) Error: Folder not found: /SERVERY/maily/@550-521_rate undefined
    r chunk-vendors.bundle.js:1954
    d chunk-vendors.bundle.js:1968
14:57:52.432
GEThttp://detectportal.firefox.com/success.txt?ipv4
[HTTP/1.1 200 OK 59ms]

14:57:52.433
GEThttp://detectportal.firefox.com/success.txt?ipv6
14:58:05.679
POSThttp://r3.o.lencr.org/
[HTTP/1.1 200 OK 57ms]

14:58:55.666 Successfully compiled asm.js code (total compilation time 141ms) demangle.js
15:00:19.693 Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”). panel.js:78:24
15:00:22.844 This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features! index.html
15:00:34.163
GEThttp://detectportal.firefox.com/success.txt?ipv4
[HTTP/1.1 200 OK 76ms]

15:00:34.165
GEThttp://detectportal.firefox.com/success.txt?ipv6
15:02:56.651
POSThttp://ocsp.int-x3.letsencrypt.org/
[HTTP/1.1 200 OK 109ms]

15:02:56.701
POSThttp://ocsp.int-x3.letsencrypt.org/
[HTTP/1.1 200 OK 62ms]
</details>

Screenshot after cca 30 min
![2021-01-24-153539_3840x1440_scrot](https://user-images.githubusercontent.com/1543288/105633915-a187d280-5e5b-11eb-935b-e911454fe9d1.jpg)

**Comment by devmount** [comment] 2021-01-24 17:34
Thank you, I will take a closer look how Search Folders (didn't know about them until you reported this 😅) are handled in the Webextension APIs and let you know, when I have a bug fix. Maybe it's also related to #19

**Comment by orgoj** [comment] 2021-01-24 18:12
The problem is probably a char '@', which I use in folder name. I try make saved search on other working account in Thirds stats. After refresh this working, if folder name not contain @ at name start. This for in problematic account, after removing all @.

**Comment by devmount** [comment] 2021-01-25 06:07
You're totally right, adding `@` to the search folder name provokes this error on my site too. I've done some debugging and unfortunately I don't see a way to identify search folders, as they don't seem to have a type property. I placed a [corresponding report at Thunderbirds topicbox](https://thunderbird.topicbox.com/groups/addons/T9512c51064524848/search-folder-recognition), let's hope somebody has an idea how to handle this.

**Comment by devmount** [comment] 2021-01-25 12:46
It looks like a Thunderbird issue, so I created a corresponding bug report:
https://bugzilla.mozilla.org/show_bug.cgi?id=1688612

Let's hope, a fix will soon be available.

**Comment by devmount** [comment] 2021-01-28 14:18
As there is nothing more to do on ThirdStats' side, I'll close this here.

**Closed by devmount** 2021-01-28 14:18 UTC
Labels: bug, thunderbird issue
